// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0y1mxOc70wtRfy1cFCv6U_W1XEqYYCAY',
    appId: '1:960135121208:web:075125b37bbce5cfdf99cd',
    messagingSenderId: '960135121208',
    projectId: 'date-keeper-date',
    authDomain: 'date-keeper-date.firebaseapp.com',
    storageBucket: 'date-keeper-date.appspot.com',
    measurementId: 'G-QB6X009Q9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxw_vHWlIPN6Vq_IBlxsTRPrz4wZ2BWMM',
    appId: '1:960135121208:android:dedc516106c5f8dedf99cd',
    messagingSenderId: '960135121208',
    projectId: 'date-keeper-date',
    storageBucket: 'date-keeper-date.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFdC0KhBvt8PN_eyLAm-QnJWBpOlYVz4',
    appId: '1:960135121208:ios:45994eab98d27e56df99cd',
    messagingSenderId: '960135121208',
    projectId: 'date-keeper-date',
    storageBucket: 'date-keeper-date.appspot.com',
    iosBundleId: 'com.example.dateKeeper',
  );

}